# i really dunno what i'm doing yet

{
    "resume": {
	"contact_info" : [
		{
          	"name": "string",
          	"email": "string",
          	"phone": "string"
		}
        ],
	"summary" : [
		{
		"description" : "string",
		"objective" : "string"
		}
	]
	"skills" : [
		{
		category: [
			{ 
			"name": "string",
				"skill" : [
					{
					"name": "string",
					"aptitude": "string",
					"aptitude_scale" : "string",
					"years_experience" : "int",
					"training": "string"
					}
				]
			}
		]
		}		
	]
        "education": [
            {
	    "institution" : [
		{
		"name":"string",
		"location": "string"
		}
	    ],
            "degree": "string",
	    "major": "string",
	    "minor": "string",
	    "specialty": "string",
            "graduation_date": "date",
	    "gpa": "float",
	    "gpa_scale": "string"
            }
        ],
        "work_experience": [
            {
                "company": "string",
                "position": "string",
                "startDate": "date",
		"end_date": "date",
		"responsibilities": "string"
            }
        ]
    }
}
